#!/usr/bin/with-contenv bash

if [ ! -f /config/www/sui.lock ]; then
  echo "**** Installing SUI  ****"
  rm -Rf /config/www/*
  git clone \
    https://github.com/jeroenpardon/sui.git \
      /tmp/sui
  rm -f \
    /tmp/sui/docker-compose.yml \
    /tmp/sui/Dockerfile \
    /tmp/sui/License.md \
    /tmp/sui/apps.json \
    /tmp/sui/links.json \
    /tmp/sui/index.html
  rm -Rf /tmp/sui/.git
  cp -Rf \
    /tmp/sui/. \
    /config/www/
  rm -Rf /tmp/sui
  touch /config/www/sui.lock
fi

# Permission Stuffs
chown -R \
  abc:abc \
    /config/www
