#!/usr/bin/with-contenv bash

# SUI
if [ ! -f /config/www/sui.lock ]; then
  echo "**** Installing SUI  ****"
  rm -f /config/www/*
  git clone \
    https://github.com/ThreadR-r/sui-dashboard-status.git \
      /config/www
  rm -Rf /tmp/sui
  touch /config/www/sui.lock
else
  echo "**** SUI already installed, skipping  ****"
fi

# Permission Stuffs
chown -R \
  abc:abc \
    /config/www
