#!/usr/bin/with-contenv bash

# Crontabs
mkdir -p \
  /config/crontabs
if [ ! -f /config/crintabs/root ]; then
  cp /etc/crontabs/root \
    /config/crontabs/
fi

# Permissions Stuffs
chown -R \
  abc:abc \
    /config/www
